### ISSUE TITLE
Thank you for the incredible resource

### ISSUE THREAD

**Issue by tyleralbee** [jasonraimondi/ts-oauth2-server-example#5]
Hi Jason, I realize this is not an issue, but I wanted to thank you somehow for this example. It is extremely rare to find a repository of well-written code that:

1. Goes into production-level depth that fully explores the intended use-cases
2. Does so for both the client and the server
3. Is limited in scope to what is truly necessary for context without making the codebase confusing

I have been dreading exploring OAuth 2.0 because of how often I hear, "don't roll your own auth". This example and `ts-oauth2-server` really made something click for me. Thank you for your hard work. I will pass along the good deed.

**Comment by jasonraimondi** [comment]
Thank you for the kind words and for your support! Stoked that these projects were able to help you learn about building your own oauth2 server.

**Comment by tyleralbee** [comment]
Absolutely. I'll close the issue; have a good one.

**Comment by jasonraimondi** [comment]
Thanks again man! Definitely super motivating to know that I'm able to help out others learn <3

**Comment by jasonraimondi** [comment]
If you have any specific questions or recommendations on improving the repository I'd be happy to answer/implement them.

**Comment by tyleralbee** [comment]
> If you have any specific questions or recommendations on improving the repository I'd be happy to answer/implement them.

I do have one recommendation: turn on GitHub discussions for the main repository. I am unsure if that's only allowed for paid plans, if that's why it's not enabled, I understand.

**Comment by jasonraimondi** [comment]
Oh that is easy, [done](https://github.com/jasonraimondi/ts-oauth2-server/discussions/127#discussion-6669370). I actually don't think I've used GH discussions too much, which is why I probably just never enabled it. Feel free to drop a line over there if you have anything else.
