### ISSUE TITLE
pnpm db:seed fails with Unknown file extension ".ts"

### ISSUE THREAD

**Issue by michielbdejong** [jasonraimondi/ts-oauth2-server-example#6]
Hi!

I get the following error on my system:
```
$ pnpm db:seed

> jmondi-oauth2-example-server@ db:seed /Users/michiel/gh/jasonraimondi/ts-oauth2-server-example
> ts-node --esm prisma/seed.ts

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/michiel/gh/jasonraimondi/ts-oauth2-server-example/prisma/seed.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:143:22)
    at async nextLoad (node:internal/modules/esm/hooks:865:22)
    at async nextLoad (node:internal/modules/esm/hooks:865:22)
    at async Hooks.load (node:internal/modules/esm/hooks:448:20)
    at async MessagePort.handleMessage (node:internal/modules/esm/worker:196:18) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
 ELIFECYCLE  Command failed with exit code 1.
```

I'll poke around to see what might be causing this, probably a problem with how my system is set up, but wanted to report it nonetheless, for reference.

I'm using a Macbook with `ts-node` version 10.9.1 and node version 20.11.0

**Comment by michielbdejong** [comment]
Hm, I was using node and pnpm through Volta, switching to nvm and npm respectively now to see if that fixes it.
Also switching from node 20 to node 18 to see if that helps.

**Comment by michielbdejong** [comment]
The problem also happens on GitPod so it seems to be unrelated to my laptop setup

**Comment by michielbdejong** [comment]
It also happens when you `ts-node empty.ts` an empty file.
If you delete `package.json` then it works!

**Comment by michielbdejong** [comment]
Specifically, removing [this line](https://github.com/jasonraimondi/ts-oauth2-server-example/blob/76909d9aa9d7a8d7e694b0cfce6a907222030f7c/package.json#L12) from package.json fixes it.

**Comment by michielbdejong** [comment]
Ah! https://stackoverflow.com/a/75990537/680454 fixes this. I'll create a PR.

**Comment by michielbdejong** [comment]
Hm, I saw this working on GitPod with Node 16 but having some trouble generalising the result. Investigating further...

**Comment by michielbdejong** [comment]
Fixed in #7

**Comment by jasonraimondi** [comment]
Thank you for looking into this and figuring out a resolution, this was next on my list! Are you all good or is there anything else I can help out with or help make more clear? If you have any suggestions to on documentation or anything, totally open to it!

**Comment by michielbdejong** [comment]
All good, thanks!
Thank you for this project and for merging the PR!
